### PR TITLE
refactor: reflect kernel pr 11757

### PR DESCRIPTION
**Pull request by arkbriar**
Upstream change: https://github.com/risingwavelabs/risingwave/pull/11757
Draft until it is released.

### CODE REVIEW

**Comment by hzxa21** [comment]
Will this change affect existing users that are already running with `hummock+xx://%s@%s`

**Comment by wcy-fdu** [comment]
I think we should keep existing users using `bucket@root`and new users(new clusters) using `bucket` only

**Comment by zwang28** [comment]
Does the code path to delete cluster need any changes? e.g. for a cluster with @, is it OK to delete its object store by path without @.

**Comment by arkbriar** [comment]
> Will this change affect existing users that are already running with hummock+xx://%s@%s

No. Helm chart is unlike the operator. It won't touch the deployment any more until the user performs another action. But the change will indeed break the compatibility between the latest chart and the older kernel versions. 

Helm has provided a way to workaround this, by specifying the chart version. Users can use older chart versions once they found the latest one incompatible with their kernel versions.

**Pull request closed without merging**
