### PR TITLE
feat: support sql meta backends and local fs state store backend

### PR DESCRIPTION
**Pull request by arkbriar**
- Support SQL backends `sqlite`, `mysql` and `postgresql`
- Support local FS state store backend
- Support `volumeClaimTemplates` and `persistentVolumeClaimRetentionPolicy` in standalone, meta and compute to persistent local files
- Add examples and test cases.
- Do a release.

After the PR's merged, one can start a pure standalone (1 pod only) with the following command:

```bash
helm install -f examples/dev/dev.values.yaml risingwave risingwavelabs/risingwave
```

The file `examples/dev/dev.values.yaml` can be found [here](https://github.com/risingwavelabs/helm-charts/blob/4d782f7b26ae5a5b0752cda0bdf47ce385039c31/examples/dev/dev.values.yaml).

### CODE REVIEW

**Comment by arkbriar** [comment]
Also, if a user just want to try out the RisingWave without considering data persistence, the following command can work on bare k8s.

```bash
helm install --set metaStore.sqlite.enabled=true,stateStore.localFs.enabled=true,standalone.enabled=true risingwave risingwavelabs/risingwave
```

**Comment by arkbriar** [comment]
Tested with sqlite, PG and MySQL, and RW version v1.7.1. 

Conclusions:
- RW works well with PG and sqlite. 
- However, RW refused to start with MySQL. It's a bug and I have let @yezizp2012 know.

```plain
mismatched types; Rust type `core::option::Option<chrono::naive::datetime::NaiveDateTime>` (as SQL type `DATETIME`) is not compatible with SQL type `TIMESTAMP`
```

**Comment by yezizp2012** [comment]
> Tested with sqlite, PG and MySQL, and RW version v1.7.1.
> 
> Conclusions:
> 
> * RW works well with PG and sqlite.
> * However, RW refused to start with MySQL. It's a bug and I have let @yezizp2012 know.
> 
> ```
> mismatched types; Rust type `core::option::Option<chrono::naive::datetime::NaiveDateTime>` (as SQL type `DATETIME`) is not compatible with SQL type `TIMESTAMP`
> ```

Opened a PR to fix several issues when using MySQL: https://github.com/risingwavelabs/risingwave/pull/15717. There is only one issue left now, and I am considering how to elegantly solve it.

**Review by yezizp2012 — APPROVED** [review]
LGTM! Thx for the job!

**Pull request merged**
